/*
 *  This file is automatically generated and does not require a license
 *
 *  ==== WARNING: CHANGES TO THIS GENERATED FILE WILL BE OVERWRITTEN ====
 *
 *  To make changes to the generated code, use the space between existing
 *      "USER CODE START (section: <name>)"
 *  and
 *      "USER CODE END (section: <name>)"
 *  comments, where <name> is a single word identifying the section.
 *  Only these sections will be preserved.
 *
 *  Do not move these sections within this file or change the START and
 *  END comments in any way.
 *  ==== ALL OTHER CHANGES WILL BE OVERWRITTEN WHEN IT IS REGENERATED ====
 *
 *  This file was generated from
 *      C:/ti/grace_2_20_01_12/packages/ti/mcu/msp430/csl/timer/ITimerx_A_init.xdt
 */

#include <msp430.h>

/* USER CODE START (section: Timer_A2_init_c_prologue) */
/* User defined includes, defines, global variables and functions */
/* USER CODE END (section: Timer_A2_init_c_prologue) */

/*
 *  ======== Timer_A2_graceInit ========
 *  Initialize MSP430 Timer_A2 timer
 */
void Timer_A2_graceInit(void)
{
    /* USER CODE START (section: Timer_A2_graceInit_prologue) */
    /* User initialization code */
    /* USER CODE END (section: Timer_A2_graceInit_prologue) */
    
    /* 
     * TACCTL1, Capture/Compare Control Register 1
     * 
     * CM_0 -- No Capture
     * CCIS_0 -- CCIxA
     * ~SCS -- Asynchronous Capture
     * ~SCCI -- Latched capture signal (read)
     * ~CAP -- Compare mode
     * OUTMOD_7 -- PWM output mode: 7 - PWM reset/set
     * 
     * Note: ~<BIT> indicates that <BIT> has value zero
     */
    TACCTL1 = CM_0 | CCIS_0 | OUTMOD_7;

    /* TACCR0, Timer_A Capture/Compare Register 0 */
    TACCR0 = 49999;

    /* TACCR1, Timer_A Capture/Compare Register 1 */
    TACCR1 = 50;

    /* 
     * TACTL, Timer_A2 Control Register
     * 
     * TASSEL_2 -- SMCLK
     * ID_0 -- Divider - /1
     * MC_1 -- Up Mode
     */
    TACTL = TASSEL_2 | ID_0 | MC_1;

    /* USER CODE START (section: Timer_A2_graceInit_epilogue) */
    /* User code */
    /* USER CODE END (section: Timer_A2_graceInit_epilogue) */
}
